name: nightly-vector-update

on:
  schedule:
    - cron: '0 2 * * *'  # UTC 02:00 (台灣 10:00)，每天執行

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare GCP SA key
      run: echo "${{ secrets.GCP_SA_KEY }}" > gcp-sa.json

    - name: List Drive images
      env:
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
      run: |
        python vector.py \
          --sa gcp-sa.json \
          --folder $DRIVE_FOLDER_ID \
          --output drive_images.json

    - name: Build FAISS index
      run: |
        python vector2.py \
          --input drive_images.json \
          --out-index image_index.faiss \
          --out-meta image_metadata.json

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: nightly-${{ github.run_id }}
        release_name: Nightly build #${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload FAISS asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: image_index.faiss
        asset_name: image_index.faiss
        asset_content_type: application/octet-stream

    - name: Upload metadata asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: image_metadata.json
        asset_name: image_metadata.json
        asset_content_type: application/json

    - name: Cleanup
      run: rm -f gcp-sa.json
